// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aknrcumzwzouxzzyjvnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbnJjdW16d3pvdXh6enlqdm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjg4MjAsImV4cCI6MjA2NTUwNDgyMH0.2Ho7YZ7NoAVAxlmkiKq1hDgxLKieobp_TbkEL3WNwOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);